services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./service-account.json:/app/service-account.json:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
      - TESTING=false
    volumes:
      - .:/app
      - ./service-account.json:/app/service-account.json:ro
    ports:
      - "8001:8000"
    depends_on:
      - api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload